### PR TITLE
Added ability to register multiple routes for a single handler

### PR DESCRIPTION
**Pull request by philipengberg**
Fairly simple, yet useful addition.

### CODE REVIEW

**Comment by joeldev** [comment]
Looks good, thanks!

**Comment by philipengberg** [comment]
Awesome, let me know when you do a new cocoapod release :+1:

**Comment by joeldev** [comment]
1.5.3 is pushed.

**Comment by philipengberg** [comment]
Fastest gun in the west :gun::wink:

**Pull request merged**
